name: first pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - uses: actions/checkout@v3

      - name: Copy .env
        run: cp .env.example .env

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress

      - name: Generate Key
        run: php artisan key:generate

      - name: Directory Permission
        run: chmod -R 777 storage bootstrap/cache

      - name: Phpstan
        run: ./vendor/bin/phpstan analyse --memory-limit=1G
